"""initial schema

Revision ID: 69953572b3bf
Revises: 6c5c7f7e4c2a
Create Date: 2024-10-22 04:33:49.766127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69953572b3bf'
down_revision = '6c5c7f7e4c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
